### ISSUE TITLE
Modules overview - přidání položek

### ISSUE THREAD

**Issue by ChroustJan** [MLAB-project/MLABweb#11]
V přehledu všech modulů by bylo dobré, kdyby v řádku pro každý modul byla možnost zapsání poznámky. Poté také volba dokumentace (nic/základní/hotovo), pro každý jazyk zvlášť. Foto(nic/špatná/dobrá). Aby nemusel existovat jiný seznam modulů, do kterého se dá psát.

**Comment by roman-dvorak** [comment]
Kvalita obrázku by měla být zhodnocena v položce 'mark'. Podle toho se také daný modul zobrazí na úvodní stránce. Jestli obrázek existuje/QRkód/žádný je v přehledu v 6. sloupci. Na tomto systému jsme se kdysi domlouvali...

![snimek obrazovky porizeny 2018-11-05 14-07-12](https://user-images.githubusercontent.com/5196729/47999906-34fe4d00-e104-11e8-8039-fee51deab0b1.png)

Stav dokumentace je v přehledu modulů vidět podle počtu znaků. Myslím, že to je docela dobrý orientační ukazatel. A je to tam v obou jazycích.

Položka 'mark' by měla zahrnovat právě i další aspekty kvality dokumentace. Např i kvalitu dokumentace, stav modulu, ...

Úplně mi z toho není jasné, co by v té poznámce mělo/mohlo být vepsáno.

**Comment by ChroustJan** [comment]
Obrázky ok. To jsem si nevšiml že můžu měnit. To počítání znaků neřeší zda jsou tam dobrá data. Třeba ty vygenerované dokumentace automatem nedávají smysl a přesto mají znaky.

Do poznámky bych si právě chtěl psát různé věci, co se nehodí nikam jinam. Třeba špatná struktura, přefotit...

**Comment by kaklik** [comment]
Ta přehledová tabulka modulů je hodně dobrá věc..  Poznámky do ní ale myslím nedávají smysl. Protože to už je issue u modulu, které by navíc mělo být někomu přiřazeno. 

Tudíž bych to viděl tak, že ta přehledová tabulka by klidně mohla být read-only.

**Comment by roman-dvorak** [comment]
Přehledovou tabulku plánuji umístit mimo web. Konkrétně tak, že se bude generovat do [.github](https://github.com/MLAB-project/.github) repozitáře, kde bude vidět, obdobným způsobem, stav jednotlivých modulů.
