### ISSUE TITLE
Nefunguje přepínání jazyka

### ISSUE THREAD

**Issue by ChroustJan** [MLAB-project/MLABweb#13]
Pokud není problém konfigurace WIN10 a Chrom, tak mi nefunguje přepínání jazyka.

**Comment by roman-dvorak** [comment]
Ano, teď jsem to testoval v Firefoxu, Chromiu a Opeře. V Chromiu mi to také nefunguje. Zkusím zjistit problém.

**Comment by povik** [comment]
Přepínání jazyka jsem otestoval ve Firefoxu a Chromiu.
