### ISSUE TITLE
Modul s ID 0 v seznamu modulů je zřejmě poškozený

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#14]
vypadá to, že má nevyplněná některá datobázová pole: 
![image](https://user-images.githubusercontent.com/1194177/50772819-4ba15b80-128f-11e9-8663-81891c439812.png)

**Comment by roman-dvorak** [comment]
Vyřeší se pomocí #16 

Toto vznikne, když se klikne tlačítko uložit nový modul a není vyplněný název položky.
