### ISSUE TITLE
Autentizace uživatele přes github se chová nepředpokládatelně

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#15]
Přihlášení má tyto problémy

- [X] 1. Tlačítko pro přihlášení není na hlavní stránce a musí se kliknout na seznam modulů, což je pro uživatele neintuitivní. 
- [x] 2. Po přihlášení je uživatel navrácen na hlavní stránku webu, kde ale není vidět, že se stal přihlášeným uživatelem
- [ ]  3. Pokud přihlášený uživatel není členem organizace MLAB-project na githubu, tak se jeho uživatelské jméno zobrazí jako None, takže uživatel ani neví, proč nemá práva na úpravy.

**Comment by roman-dvorak** [comment]
Bod č. 1 vyřešen. Na úvodní stránku je přidáno přihlašovací tlačítko.

**Comment by kaklik** [comment]
Bod č. 2 je tím myslím zároveň vyřešen také, neboť je teď i na hlavní stránce vidět, že je uživatel přihlášený.
