### ISSUE TITLE
Změnit pojmenování polí "Dlouhý název", "Krátký popis"

### ISSUE THREAD

**Issue by roman-dvorak** [MLAB-project/MLABweb#18]
Pojmenování textových polí je trošku zaváděící. Pro některé lidi může být velmi zmatečné.

Navrhuji takovéto pojmenování:
- Název (USBI2C01A)
- Rozšířený název/podnadpis (Převodník z USB na I²C master)
- Stručný popis (kratší odstaveček ~100 slov)
- podrobný popis/dokumentace

Další varianta mě napadá (ve sejném pořádí):
- Výrobní kód
- Název
- Stručný popis
- podrobný popis/dokumentace

Jaký názor máš na to názor @ChroustJan? Klině navrhni jiné.

Bohužel jsou velmi podobně pojmenovány i pole v .json souborech.

<bountysource-plugin>

- [X]  Úprava popisků ve webovém rozhraní
- [ ] Změna názvů parametrů v Json souborech.

**Comment by ChroustJan** [comment]
Já bych byl pro tuto verzi:
Název
Podnadpis (Převodník z USB na I²C master)
Stručný popis (kratší odstaveček ~100 slov)
Dokumentace

Pokud to není problém, tak v tom editu modulu je místo i na ten obsah v závorce. U názvu bych příklad nedával.

**Comment by roman-dvorak** [comment]
Popisky ve webovém rozhraní změněny.
