### ISSUE TITLE
Pozice filtru v seznamu modulů

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#2]
Miho si stěžuje, že filtr stavu modulů by měl být rovnou rozbalený ve stejném řádku, jako je tlačítko filtr. 

![image](https://user-images.githubusercontent.com/1194177/35978238-7454434a-0ce5-11e8-9728-b85d393f8722.png)

**Comment by kaklik** [comment]
Od @taury55 máme nové zjištění, že si nerozbaleného filtru vůbec nevšimne.  Je to tak stejná situace jako s Mihem.

**Comment by roman-dvorak** [comment]
Filtr je nyní vždy viditelný
