### ISSUE TITLE
Poznámka o open-source hardware

### ISSUE THREAD

**Issue by povik** [MLAB-project/MLABweb#24]
Každá stránka s modulem může mít poznámku jako: This is an open-source hardware design, one of the modules from the MLAB brick system.

**Comment by kaklik** [comment]
Tohle dává smysl, navíc se ale ukazuje, že lidi neví co to ten open-source je. Tudíž by tam asi měl být odkaz na [Wikipedii](https://en.wikipedia.org/wiki/Open-source_hardware).

Alternativou k tomu by bylo tam mít symbol [OSHWA certifikace](https://certification.oshwa.org/). S tím je ale potíž, že to asi dává smysl jen u složitějších zařízení, protože ten proces je poměrně komplikovaný a trvá dlouho.

**Comment by roman-dvorak** [comment]
Ten kdo neví, co je opensource nebude vědět co je OSHWA, ale ano, měli bychom někdy zkusit si zaregistrovat OSHWA zařízení. 

Jo, nějakou poznámku o open-source návrhu zakomponuji.

**Comment by kaklik** [comment]
> Ten kdo neví, co je opensource nebude vědět co je OSHWA, ale ano, měli bychom někdy zkusit si zaregistrovat OSHWA zařízení.

Pokud to ten návštěvník neví, tak stačí, že ta poznámka bude vypadat důležitě a zároveň bude mít možnost si to prokliknout na místo, kde mu to vysvětlí.
Zatím jsem tam zkoušel zaregistrovat LABDOS a TFRPM01, žádost se stále vyřizuje. 

> 
> Jo, nějakou poznámku o open-source návrhu zakomponuji.

**Comment by roman-dvorak** [comment]
![obrazek](https://github.com/MLAB-project/MLABweb/assets/5196729/80f47b2d-1259-4e48-ad3d-c4dc157b6942)

Poznámka o open-source HW přidána. Až budeme mít MLAB modul s OSHWA, tak tam přidám nějakou ikonku.
