### ISSUE TITLE
Odkaz na filtrovaný seznam modulů

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#26]
Aktuální provedení zřejmě neumí odkázat na ofiltrovaný seznam modulů s vyhledáváním. Například na následující pohled nejde odkázat, neboť odkaz vypadá takhle: `https://www.mlab.cz/modules?status=2`

![image](https://user-images.githubusercontent.com/1194177/78347993-9482b580-75a1-11ea-94a3-f0d4ff284a7f.png)

**Comment by roman-dvorak** [comment]
Nyní se vytvoří odkaz https://www.mlab.cz/modules?status=2&search=I2CADC, který lze sdílet.
