### ISSUE TITLE
Web neumí pracovat se submoduly

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#28]
V souvislosti se snahou z https://github.com/MLAB-project/Modules/issues/7  která vede na to, že jednotlivé moduly jsou vlastní repozitáře a do společného repozitáře jsou přidávány jako submoduly. Což umožňuje přidávat i externí moduly. 

Tak vzniká problém s tím, že současný webový nástroj submoduly v repozitáři nezná. 
V důsledku toho vznikají na webu, jakoby prázdné moduly. Příkladem je třeba [USBRS232](https://www.mlab.cz/module/USB232R01B).

**Comment by kaklik** [comment]
Jako dočasné řešení bych navrhoval mlabweb upravit tak, aby byl pouze read-only. Což znamená že veškeré parametry a dokumentace modulů by se měnily pouze přes github.

**Comment by roman-dvorak** [comment]
MLABweb je nyní read-only. Neumožňuje žádnou editaci.. Všechny moduly jsou nyní umístěny do organizace MLAB-modules a využívá se pouze ta. Web je z ní pravidelně aktualizován. 

Je potřeba zdokumentovat co lze nastavovat a jak.
