### ISSUE TITLE
v případě že se status=2  vymění za něco jiného

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#29]
Tak to vybleje vnitřnosti.

https://www.mlab.cz/modules?status=tosu

Tohle chování je obecně považováno za bezpečnostní zranitelnost.

**Comment by roman-dvorak** [comment]
Vyřešeno vypnutím debuge režimu. 

![obrazek](https://github.com/MLAB-project/MLABweb/assets/5196729/a146b9ab-6c7f-4145-8f56-5e6780242a4d)


Tento problém se týkal všech neexistujících  nebo chybných adres.
