### ISSUE TITLE
Status modulů a jejich výroba

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#30]
s @ChroustJan  často řešíme otázku které moduly poslat do výroby na panelu. Pokud by status modulů reflektoval jejich skutečný stav a připravenost k výrobě. Tak by bylo možné panely sestavovat podle těchto stavů. 
Tím by se zoptimalizovala rychlost výroby nových modulů.

**Comment by ChroustJan** [comment]
Že by se to řešilo nějak často, si nejsem moc vědom. To že je modul hotový, neznamená, že půjde do sériové výroby.

**Comment by kaklik** [comment]
Tohle issue nepopisuje sériovou výrobu, ale sestavování panelů pro prototypovou výrobu nových modulů.

**Comment by kaklik** [comment]
> Že by se to řešilo nějak často, si nejsem moc vědom. To že je modul hotový, neznamená, že půjde do sériové výroby.

Tohle issue nepopisuje sériovou výrobu, ale sestavování panelů pro prototypovou výrobu nových modulů.

**Comment by roman-dvorak** [comment]
Potřeboval bych nějakým způsobem projít všechny moduly a u nich určit jejich vyrobitelnost a jejich aktuálnost. Tyto stavy je potřeba uložit do doc/metadata.yaml

**Comment by kaklik** [comment]
> Potřeboval bych nějakým způsobem projít všechny moduly a u nich určit jejich vyrobitelnost a jejich aktuálnost. Tyto stavy je potřeba uložit do doc/metadata.yaml

A kam se to tam má uložit? Protože v [tom yaml](https://github.com/mlab-modules/PERISTALTIC01/blob/PERISTALTIC01A/doc/metadata.yaml) nevidím žádnou připravenou kolonku.

**Comment by roman-dvorak** [comment]
Na webu je zelený proužek a filtr, kterým lze vybírat stav modulů:
![obrazek](https://github.com/MLAB-project/MLABweb/assets/5196729/8b603185-a976-4acb-b256-cd5631cbcdd0)

To je v yaml souboru parametr 'status', který může mít hodnotu 1-5, pokud není uvedena, tak se aplikuje 2.
Hodnota 4 (replaced) se automaticky nastaví ve webserveru v případě, že součástka má nastavený atribur [replaced](https://github.com/mlab-modules/USB232R01/blob/USB232R01B/doc/metadata.yaml#L24)

Pak existuje hodonota 'mark', což by taktéž mělo odrážet stav modulu ve smyslu jak moc má dobrou dokumentaci, jak moc je ten modul kompletní. Neexistuje ale nějaký popis toho, co odpovídá jakému číslu. Je to rozsah 0-100, tuším, že ty moduly s dobrou dokumentací mají hodnocení okolo 80-90 (já tam nechávám nějakou rezervu). Zde předpokládám, že tohle číslo bude způsobovat výchozí řazení na webu.

Další parametr je ```homepage: true/false```, což způsobí, že se to zobrazí na úvodní stránce, Tam mám odhad, že by nemělo být více než cca 12 modulů.

**Comment by kaklik** [comment]
> To je v yaml souboru parametr 'status', který může mít hodnotu 1-5, pokud není uvedena, tak se aplikuje 2. Hodnota 4 (replaced) se automaticky nastaví ve webserveru v případě, že součástka má nastavený atribur [replaced](https://github.com/mlab-modules/USB232R01/blob/USB232R01B/doc/metadata.yaml#L24)
> 

Připadá mi divné, že hodnota 2 status znamená "Production". Očekával bych, že moduly, které to nemají uvedené, tj. někdo je právě založil. Tak budou buď Proposal, nebo In development. Hledal jsem to teď v kódu, jestli ta škála není náhodou od 0 (tj. měly by nyní správně takové moduly mít hodnotu 1 místo 2), ale nemůžu jednoznačně najít místo, které řeší default situaci.

**Comment by roman-dvorak** [comment]
Když jsem na to issue odpovídal, tak jsem to ověřoval v kódu. 

Tohle mi nepřipadá špatně. Špatně je to, že v generátoru metadat se nastaví hodnota dva i pro nové moduly. Tuším, že v tom generátoru je někde výjimka, kde se tohle nastavuje.

**Comment by kaklik** [comment]
> Když jsem na to issue odpovídal, tak jsem to ověřoval v kódu.
> 
> Tohle mi nepřipadá špatně. Špatně je to, že v generátoru metadat se nastaví hodnota dva i pro nové moduly. Tuším, že v tom generátoru je někde výjimka, kde se tohle nastavuje.

A jak ten generátor pozná nový modul? Mě připadá, že aktuálně zřejmě všechny moduly mají jakoby nastaveno dva (nevim jestli mezi nimi jsou i nějaký který to mají skutečně nastavený, ale většina nemá nastaveno nic). Pak ještě existuje několik vyjímek, který mají nastaveno replaced. 

Dá se teď udělat to, že to projdu a těm modulům, který nejsou v production něco nastavim. Byl bych ale nerad, kdyby to nějaký následný krok přepsal, jako se to vlastně stalo v případě těch json dat.

**Comment by kaklik** [comment]
> Když jsem na to issue odpovídal, tak jsem to ověřoval v kódu.
> 
> Tohle mi nepřipadá špatně. Špatně je to, že v generátoru metadat se nastaví hodnota dva i pro nové moduly. Tuším, že v tom generátoru je někde výjimka, kde se tohle nastavuje.

Přijde mi, že ten filtr nefunguje tak, jak popisuješ. Vyzkoušel jsem na dvou modulech je dostat mimo "production" kategorii, která je vidět na webu a ani u jednoho to nezafungovalo. Konkrétně to jsou tyhle:

- https://github.com/mlab-modules/PERISTALTIC01/blob/PERISTALTIC01A/doc/metadata.yaml
- https://github.com/mlab-modules/HEATBEDMAG01/blob/master/doc/metadata.yaml

Přijde mi, že ten status je vždycky "production" nezávisle na tom co obsahuje ten soubor yaml.

**Comment by kaklik** [comment]
Myslím že tohle je již vyřešené. V production stavu jsou nyní moduly, které byly už alespoň někde profesionálně vyrobeny.
