### ISSUE TITLE
Module documentation editor

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/MLABweb#31]
Od nástroje pro tvorbu dokumentací modulů potřebujeme: 

- Webové rozhraní (aby bylo možné soubory editovat bez instalace specialního software)
- Zdrojový soubor součástí repozitáře modulu ve formátu, který půjde editovat i offline a ručně treba v textovém editoru 
- Možnost exportu PDF a html souborů pro tisk a vystavení na webu. Soubory by měly být exportovány podle předem definovaného stylu
- Možnost přípravy obsahové šablony

**Comment by kaklik** [comment]
Trochu jsem tohle téma diskutoval s @petrvelicka, který navrhuje několik nástrojů, které by tyto potíže mohly vyřešit. 

- https://katex.org/
- ja osobne na psani markdownu pouzivam https://gitlab.gnome.org/World/apostrophe - umi to vygenerovat jak html tak i pdf
- pdf a html by mel umet pandoc

> ted jsem nasel, ze jsou servisy, ktere ti ihned vygeneruji z latexu obrazek, viz napr. https://latex.codecogs.com/svg.latex?\Large&space;x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}

Takový postup by umožňoval mít v markadownu vzorce, což markdown sám od sebe neumí. Markdown má oproti LaTeX výhodu, že je nutné psát méně kódu při tvorbě dokumentu.

**Comment by kaklik** [comment]
Zjistil jsem že editor souborů, který používá github je tenhle: https://codemirror.net/  
Myslím že je to tak dobré řešení, že bychom vůbec nemuseli mít editační okno pro textové soubory na našem webu.

**Comment by roman-dvorak** [comment]
Editace nebude probihat z webu
