### ISSUE TITLE
Při vytváření nového modelu cestu k němu vybírat ze seznamu

### ISSUE THREAD

**Issue by roman-dvorak** [MLAB-project/MLABweb#6]
Na stránce "editace modulu" položku root udělat jako selectbox.
Položky vytvářet procházením adresářové struktury do určité hloubky (3) a vyřazovat složky, které obsahují .json.

**Comment by ChroustJan** [comment]
Bylo by dobré, aby se automaticky vyplnila sekce kategorie podle root. Dost se nato zapomíná a pak není modul vidět v dané kategorii na webu. Z 99% kategorie odpovídá sekci root.

**Comment by roman-dvorak** [comment]
Nyní při vytváření nového modulu, uživatel vybírá z předpřipravených cest.
Po výběru cesty se automaticky vybere i kategorie. Tu má užívatel možnost vždy změnit. 

Na stránce pro editaci je nové tlačítko, které spustí automatický výběr kategorie i pro existující moduly.
