### ISSUE TITLE
V seznamu modulů udělat tlačítko vybrat vše a zrušit výběr

### ISSUE THREAD

**Issue by roman-dvorak** [MLAB-project/MLABweb#7]
Přidat tlačítka vybrat všechny úrovně vývoje a označit vše (tím tlačítkem zvolit jen zelenou kategorii)

**Comment by kaklik** [comment]
Podobného chování jsem si všiml i u toho prototypu nového webu, kdy není možné "odznačit kategorii". Chápu proč to tak je a že to vyplývá z té implementace.  Uživatelsky mi to ale přijde nepraktické.

**Comment by roman-dvorak** [comment]
hm.. to se musí udělat tím tlačítkem "zobrazit všechno" .. možná tam někde může být výraznější odkaz.

**Comment by kaklik** [comment]
> hm.. to se musí udělat tím tlačítkem "zobrazit všechno" .. možná tam někde může být výraznější odkaz.

Ono by možná bylo logické mít přímo kategorii "all modules".  To mi přijde jako celkem akceptovatelný.

**Comment by roman-dvorak** [comment]
Aktuálně mi toto issue nepřipadá důležité. Nyní je tam tlačítko "All modules", který to částečně řeší. A při vyhledávání se vyhledává přes všechny moduly.
