### ISSUE TITLE
Návrat z modulu po hledání

### ISSUE THREAD

**Issue by ChroustJan** [MLAB-project/MLABweb#9]
@roman-dvorak 

Po vyhledání modulů pomocí hledání, když se otevře nějaký vyhledaný modul a dá se zpět, tak se musí opět dát hledat. Je to značně nepříjemné.

**Comment by kaklik** [comment]
Myslím, že optimálním řešením tohoto stavu by bylo automatické otevírání stránky s madulem v novém tabu.  Stejně jako je to u intranetu.

**Comment by kaklik** [comment]
Tahle záležitost asi hodně souvisí se způsobem odkazování na vyhledávání. #26. Protože vyhledávání nyní nemění URL stránky, tudíž se prohlížeč nemá kam smysluplně vrátit.

**Comment by roman-dvorak** [comment]
Některé odkazy se nyní otevírají v novém panelu.
